export const logos = [
    { name: "miracle", logo: "/home_preview/assets/img/partners/partner.png" },
    { name: "RAJAH'S Butcher", logo: "/home_preview/assets/img/partners/partner1.png" },
    { name: "Whosedm", logo: "/home_preview/assets/img/partners/partner2.png" },
    { name: "Whosedm", logo: "/home_preview/assets/img/partners/partner3.png" },
    { name: "L3AD", logo: "/home_preview/assets/img/partners/partner4.png" },
    { name: "PieStack", logo: "/home_preview/assets/img/partners/partner5.png" },
    { name: "Sportsball", logo: "/home_preview/assets/img/partners/partner6.png" },
    { name: "PepTalk", logo: "/home_preview/assets/img/partners/partner7.png" },
    { name: "Ried daytona", logo: "/home_preview/assets/img/partners/partner8.png" },
    { name: "Partner 9", logo: "/home_preview/assets/img/partners/partner9.png" },
    { name: "Partner 10", logo: "/home_preview/assets/img/partners/partner10.png" },
    { name: "Partner 11", logo: "/home_preview/assets/img/partners/partner11.png" },
    { name: "Partner 12", logo: "/home_preview/assets/img/partners/partner12.png" },
    { name: "Partner 13", logo: "/home_preview/assets/img/partners/partner13.png" },
    { name: "Partner 14", logo: "/home_preview/assets/img/partners/partner14.png" },
    { name: "Partner 15", logo: "/home_preview/assets/img/partners/partner15.png" },
    { name: "Partner 16", logo: "/home_preview/assets/img/partners/partner16.png" },
    { name: "Partner 17", logo: "/home_preview/assets/img/partners/partner17.png" },
    { name: "Partner 18", logo: "/home_preview/assets/img/partners/partner18.png" },
    { name: "Partner 19", logo: "/home_preview/assets/img/partners/partner19.png" },
    { name: "Partner 20", logo: "/home_preview/assets/img/partners/partner20.png" },
    { name: "Partner 21", logo: "/home_preview/assets/img/partners/partner21.png" },
    { name: "Partner 22", logo: "/home_preview/assets/img/partners/partner22.png" },
    { name: "Partner 23", logo: "/home_preview/assets/img/partners/partner23.png" },
    { name: "Partner 24", logo: "/home_preview/assets/img/partners/partner24.png" },
    { name: "Partner 25", logo: "/home_preview/assets/img/partners/partner25.png" },
    { name: "Partner 26", logo: "/home_preview/assets/img/partners/partner26.png" },
    { name: "Partner 27", logo: "/home_preview/assets/img/partners/partner27.png" },
    { name: "Partner 28", logo: "/home_preview/assets/img/partners/partner28.png" },
    { name: "Partner 29", logo: "/home_preview/assets/img/partners/partner29.png" },
    { name: "Partner 30", logo: "/home_preview/assets/img/partners/partner30.png" },
  ];
