export const logos = [
  { name: "Momentum Fitness", logo: "/home_preview/assets/img/OurPartners/5561.MomentumFitness.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5562(1).png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5562(2).png" },
  { name: "Hunbul Tex Pvt Ltd", logo: "/home_preview/assets/img/OurPartners/5566.HunbulTexPvtLtd.png" },
  { name: "Maxim Agri Pvt Ltd", logo: "/home_preview/assets/img/OurPartners/5584.MaximAgriPvtLtd.png" },
  { name: "Acamar", logo: "/home_preview/assets/img/OurPartners/5611.AcamarLogo.png" },
  { name: "Hamza Arcade", logo: "/home_preview/assets/img/OurPartners/5618.HamzaArcade.png" },
  { name: "CNL UK", logo: "/home_preview/assets/img/OurPartners/5636.CNLUK.png" },
  { name: "Pakistan Army", logo: "/home_preview/assets/img/OurPartners/5639.PakistanArmy.png" },
  { name: "Punjab Food Authority", logo: "/home_preview/assets/img/OurPartners/5646.Punjab_Food_Authority_logo.png" },
  { name: "Momin Solutions", logo: "/home_preview/assets/img/OurPartners/5662.Momin-Solutions.png" },
  { name: "Masaud Tech", logo: "/home_preview/assets/img/OurPartners/5682.MasaudTech.png" },
  { name: "USA Pearl", logo: "/home_preview/assets/img/OurPartners/5687.USAperalLOGO-E.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5689.Logo.png" },
  { name: "Access", logo: "/home_preview/assets/img/OurPartners/5696.Accesslogo-1.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5705.Logo-1.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5717.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5719.Logo.png" },
  { name: "Bahria University", logo: "/home_preview/assets/img/OurPartners/5720.bahria-university-logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5721.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5730.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5762.Logo.png" },
  { name: "Shumaila's", logo: "/home_preview/assets/img/OurPartners/5767.ShumailasLogo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5770.Logo.png" },
  { name: "ZAK", logo: "/home_preview/assets/img/OurPartners/5806.zak-logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5826.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5850.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5853.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5867.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5890.GLogo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5891.Logo.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5897.Logo_B.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5906.logo.png" },
  { name: "Arafat", logo: "/home_preview/assets/img/OurPartners/5920.LogoArafat.png" },
  { name: "Cravings", logo: "/home_preview/assets/img/OurPartners/5950.CravingsLogoEPS.png" },
  { name: "Partner", logo: "/home_preview/assets/img/OurPartners/5952.Logo.png" },
  { name: "HPI", logo: "/home_preview/assets/img/OurPartners/5958.hpi-logo-dark.png" },
  { name: "Datum Labs", logo: "/home_preview/assets/img/OurPartners/5991.Datumlabs-logo.png" },
  { name: "GA Family Restaurant", logo: "/home_preview/assets/img/OurPartners/GA_Family_Restaurant_logo_upscaled_4096.png" },
  { name: "TechScale", logo: "/home_preview/assets/img/OurPartners/TechScale.png" },
];
